### PR TITLE
Added pulp_repo custom type

### PR DESCRIPTION
**Pull request by rothgar**
See README for usage and examples.

### CODE REVIEW

**Comment by i11** [comment]
Any progress guys? It would be great to finally have this type.

**Comment by rothgar** [comment]
Someone just last week brought up an issue where feed_cert and feed_key are ignored on repo creation. There is also a bug where multiple sync_schedules are created that I haven't looked at.

I'll try to get the feed_cert and feed_key working this week. Everything at that point should work as advertised with just some minor bugs to deal with.

**Comment by rbarlow** [comment]
Hello @rothgar! I've been looking at this PR. First, apologies that it has been ridiculously long since we've looked at it. We don't have any Puppet or Ruby experts on our team, so I think we've all been shy about it.

I got a friend who knows Puppet and Ruby to check it out, and so I feel comfortable merging. I also tried out the code and it does appear to work. Thanks!

One thing - we have a policy of having all commits being atomic. I tried to squash all the commits in this pull request into one, and something seems to be odd about them (they seem to conflict). I think this might be the reason the README.md file has some of the example cope repeated.

Can you squash the commits into one, resolving the conflicts? Let me know when you are done with that and I'll test it again.

One more thing you should know - the Katello project has also independently developed a Puppet module for Pulp. We have been talking with them about eliminating this Puppet module in favor of theirs since they have Puppet and Ruby experts on their project. It would be better to have one module than two anyway, and then the Pulp project wouldn't have PRs that sit for so long either. We haven't decided for sure what we will do, but I wanted to let you know that this module might have an uncertain future.

Sorry again for the long delay.

**Comment by rothgar** [comment]
@rbarlow I haven't spent much time on this because I've moved from stand alone pulp to katello. If they have a manifest that does the same thing I'd probably rather people use that because I am no ruby expert. Even this custom type has some known bugs (duplicate schedules).
Maybe it would be better for me to look at katello's custom type and merge features into it if any are lacking.
This first hack could be closed, save me time rebasing and squashing commits and then a single custom type could be used moving forward.
How does that sound?

**Comment by rbarlow** [comment]
@rothgar That sounds good to me. Again, we are very sorry for taking so long with your pull request. Hopefully we will be able to merge with Katello's to avoid these problems in the future!

**Comment by rothgar** [comment]
Just for clarification, is this the katello puppet repo you were referencing? https://github.com/Katello/puppet-pulp
I don't see any repo creating options there but could talk to them if they would even want me to add them to their module.

**Comment by rbarlow** [comment]
On 06/02/2015 03:47 PM, Justin Garrison wrote:
> Just for clarification, is this the katello puppet repo you were
> referencing? https://github.com/Katello/puppet-pulp
> I don't see any repo creating options there but could talk to them if
> they would even want me to add them to their module.

Yes, that is correct. I believe that module is maintained much more
actively than our own is. It is true that they do not have all the
features that we have, and we also do not have all the features they
have. Hopefully, we will be able to achieve something together so we
don't have to maintain two!

-- 
Randy Barlow

**Pull request closed without merging**
