### PR TITLE
Deprecate this repository.

### PR DESCRIPTION
**Pull request by bowlofeggs**

### CODE REVIEW

**Comment by ipanova** [comment]
@maxadamo we do not support this already for 2+ years, but yet we are very welcoming contributions from the community.
As @bowlofeggs mentioned please do open an issue here https://pulp.plan.io/issues/new where we can start the discussion of whether it make sense to bring the module up to date or not.
Please also note that here the puppet module is maintained and up-to-date https://github.com/theforeman/puppet-pulp
Thank you.

**Comment by maxadamo** [comment]
@ipanova I would never push you to work on this module, especially, with the explanation given by @bowlofeggs => _there is another module made by Katello, which works pretty well._ 
### I try to explain:
The puppet modules have one copy on Puppet Forge ( in this case https://forge.puppet.com/pulp/pulp ) and the source code elsewhere (in many cases is Github). 
Unfortunately the copy on Puppet Forge of this module is one commit back from more 2 years, and it does **not** contain the deprecation notice. 
### What happens in this case: 
people goes on Puppet Forge (the only place where puppet modules are being downloaded), download that copy, which has no deprecation notice, and waste several hours, before realizing that the module could never work. 
### what we're asking:
could you please release a new version on Puppet Forge, to let people immediately understand the situation? 
You could even explain, that there is an undergoing discussion, but please do not let people waste a lot of time for nothing.

**Comment by maxadamo** [comment]
### At same time:
@bowlofeggs  stated clearly: "we do not accept new pull requests" 
@ipanova  says: "we are very welcoming contributions" 
please, clean the mess :) 
Thanks a lot.

**Comment by ipanova** [comment]
I see, thanks for explanation. We'll try to sort this out not to cause pain
and loss of peoples' time.

2 мая 2018 г. 8:14 ПП пользователь "Massimiliano Adamo" <
notifications@github.com> написал:

@ipanova <https://github.com/ipanova> I would never push you to work on
this module, especially, with the given explanation from @bowlofeggs
<https://github.com/bowlofeggs>: there is another module made by Katello,
which work pretty well.
I try to explain:

The puppet modules have one copy on Puppet Forge (
https://forge.puppet.com/pulp/pulp ) and the source code elsewhere (in many
case is Github).
Unfortunately the copy on Puppet Forge of this module is one commit back
from more 2 years, and it does *not* contain the deprecation notice.
What happens in this case:

people goes on Puppet Forge, download *that* copy, which has no deprecation
notice, and waste several hours, before realizing that this module could
never work.
what we're asking:

could you please release a new version on Puppet Forge, to let people
immediately understand the situation?
You could even explain, that there is an undergoing discussion, but please
do not let people waste a lot of time for nothing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pulp/puppet_deployment/pull/27#issuecomment-386071319>,
or mute the thread

**Comment by ipanova** [comment]
module is removed. thanks for bringing this up.

**Pull request merged**
