### PR TITLE
Use the new build env on Travis

### PR DESCRIPTION
**Pull request by joshk**
more ram, dedicated cpu cores, better networking, awesome boot times

### CODE REVIEW

**Comment by rbarlow** [comment]
This PR seems to have failed in Travis.

**Comment by rbarlow** [comment]
Can you squash your two commits into one? This looks reasonable to me, so I'll merge it when that is done. Thanks!

**Comment by joshk** [comment]
Sorry, not able to do this via the UI, and don't have the time to do this locally right now.

**Comment by rbarlow** [comment]
Hi @joshk! Have you found time to squash the commits? Thanks!

**Comment by joshk** [comment]
no sorry, no time right now, at a conf this week, then some time off with family. feel free to implement the changes yourself if you prefer.

High 5

**Comment by rbarlow** [comment]
I squashed your commits into one, and I think I was able to maintain your authorship too. See https://github.com/pulp/puppet_deployment/pull/15.

**Pull request closed without merging**
